export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const GET_SPECIFIC_CATEGORY = "GET_SPECIFIC_CATEGORY";
export const GET_ERROR = "GET_ERROR";

export const GET_ALL_BRAND = "GET_ALL_BRAND";
export const CREATE_BRAND = "CREATE_BRAND";
export const GET_SPECIFIC_BRAND = "GET_SPECIFIC_BRAND";

export const CREATE_SUB_CATEGORY = "CREATE_SUB_CATEGORY";
export const GET_ALL_CATEGORY_SUB_CATEGORY = "GET_ALL_SUB_CATEGORY";

export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT";
export const GET_SPECIFIC_PRODUCT = "GET_SPECIFIC_PRODUCT";
export const GET_CATEGORY_PRODUCTS = "GET_CATEGORY_PRODUCTS";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const GET_ALL_PRODUCT_CATEGORY = "GET_ALL_PRODUCT_CATEGORY";
export const GET_ALL_PRODUCT_BRAND = "GET_ALL_PRODUCT_BRAND";

export const CREATE_NEW_USER = "CREATE_NEW_USER";
export const LOGIN_USER = "LOGIN_USER";
export const FORGET_PASSWORD = "FORGET_PASSWORD";
export const VERIFY_PASSWORD = "VERIFY_PASSWORD";
export const RESET_PASSWORD = "RESET_PASSWORD";

export const CREATE_REVIEW = "CREATE_REVIEW";
export const All_REVIEWS_PRODUCT = "All_REVIEWS_PRODUCT";
export const DELETE_REVIEW = "DELETE_REVIEW";
export const EDIT_REVIEW = "EDIT_REVIEW";

export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
export const DELETE_FROM_WISHLIST = "DELETE_FROM_WISHLIST";
export const GET_ALL_WISHLIST = "GET_ALL_WISHLIST";

export const CREATE_COUPON = "CREATE_COUPON";
export const GET_ALL_COUPONS = "GET_ALL_COUPONS";
export const DELETE_COUPON = "DELETE_COUPON";
export const GET_SPECIFIC_COUPON = "GET_SPECIFIC_COUPON";
export const EDIT_SPECIFIC_COUPON = "EDIT_SPECIFIC_COUPON";

export const ADD_ADDRESS = "ADD_ADDRESS";
export const GET_ALL_ADDRESSES = "GET_ALL_ADDRESSES";
export const DELETE_ADDRESS = "DELETE_ADDRESS";
export const GET_SPECIFIC_ADDRESS = "GET_SPECIFIC_ADDRESS";
export const EDIT_ADDRESS = "EDIT_ADDRESS";
export const UPDATE_USER_DATA = "UPDATE_USER_DATA";
export const UPDATE_USER_PASSWORD = "UPDATE_USER_PASSWORD";

export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const GET_ALL_PRODUCT_CART = "GET_ALL_PRODUCT_CART";
export const DELETE_ALL_CART = "DELETE_ALL_CART";
export const DELETE_SPECIFIC_CART_PRODUCT = "DELETE_SPECIFIC_CART_PRODUCT";
export const UPDATE_PRODUCT_CART_COUNT = "UPDATE_PRODUCT_CART_COUNT";
export const APPLY_COUPON = "APPLY_COUPON";

export const CREATE_CASH_ORDER = "CREATE_CASH_ORDER";
export const GET_ALL_ORDERS = "GET_ALL_ORDERS";
export const GET_SPECIFIC_ORDER = "GET_SPECIFIC_ORDER";
export const CHANGE_ORDER_PAID = "CHANGE_ORDER_PAID";
export const CHANGE_ORDER_DELIVER = "CHANGE_ORDER_DELIVER";
export const CREATE_CARD_ORDER = "CREATE_CARD_ORDER";
